import os
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

REPORT_FOLDER = "static/reports"
os.makedirs(REPORT_FOLDER, exist_ok=True)


def generate_report(
        filename,
        disease,
        confidence,
        probabilities):

    pdf_path = os.path.join(
        REPORT_FOLDER,
        filename.replace(".jpg", ".pdf").replace(".png", ".pdf")
    )

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    elements = []

    title = Paragraph(
        "<b>Skin Disease Diagnosis Report</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Spacer(1,20))

    elements.append(
        Paragraph(
            f"<b>Predicted Disease:</b> {disease}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Confidence:</b> {confidence:.2f} %",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1,20))

    data = [["Disease","Probability (%)"]]

    for item in probabilities:

        data.append([

            item["class"],

            f'{item["probability"]:.2f}'

        ])

    table = Table(data)

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.darkblue),

            ("TEXTCOLOR",(0,0),(-1,0),colors.white),

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("BACKGROUND",(0,1),(-1,-1),colors.beige),

            ("ALIGN",(0,0),(-1,-1),"CENTER"),

            ("BOTTOMPADDING",(0,0),(-1,0),12),

        ])

    )

    elements.append(table)

    elements.append(Spacer(1,20))

    elements.append(

        Paragraph(

            "This report is generated by the Skin Disease Classification System using a Deep Learning model.",

            styles["Italic"]

        )

    )

    doc.build(elements)

    return pdf_path